# create a docker-compose.yml file
version: "2"
services:
  web:
    build: .
    ports:
      - "8006:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - TARGET=http://192.168.4.28:8081
    #volumes:
    #  - .:/app
      #- ./package.json:/app/package.json:z
      #- ./src:/app/src
      #- ./config:/app/config
      #- ./build:/app/build
