# create a docker-compose.yml file
version: "3"
services:
  web:
    container_name: one-team-web
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    ports:
      - "8006:8006"
    external_links:
      - one-team-server:oneteamweb-back

